apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemonset
spec:
  selector:
    matchLabels:
      app: my-agent
  template:
    metadata:
      labels:
        app: my-agent
    spec:
      containers:
      - name: agent
        image: busybox:latest
        command:
          - sh
          - -c
          - tail -F /app/logs/app.log
        volumeMounts:
        - name: logs
          mountPath: /app/logs
          readOnly: true
      volumes:
      - name: logs
        hostPath:
          path: /var/log/my-app
          type: DirectoryOrCreate
