apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: app
          image: antonglinisty/my-app
          volumeMounts:
            - name: logs
              mountPath: /app/logs/
          envFrom:
            - configMapRef:
                name: my-configmap
          readinessProbe:
              failureThreshold: 3
              httpGet:
                  path: /status
                  port: 5000
              periodSeconds: 30
              successThreshold: 1
              timeoutSeconds: 1
          livenessProbe:
              failureThreshold: 3
              httpGet:
                  path: /status
                  port: 5000
              periodSeconds: 30
              successThreshold: 1
              timeoutSeconds: 1
          startupProbe:
              failureThreshold: 10
              httpGet:
                  path: /status
                  port: 5000
              periodSeconds: 30
      volumes:
        - name: logs
          hostPath:
            path: /var/log/my-app/
            type: DirectoryOrCreate
