apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: app
          image: antonglinisty/my-app
          volumeMounts:
            - name: logs
              mountPath: /app/logs
          envFrom:
            - configMapRef:
                name: my-configmap
      volumes:
        - name: logs
          emptyDir: {}
